name: Docker build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: Build and package with Maven
        run: mvn --no-transfer-progress -B package -DskipTests

      - name: Login to Amazon ECR
        uses: aws-actions/aws-ecr-login@v1
        with:
          registry: ${{ secrets.AWS_ECR_REGISTRY }}
          region: ${{ secrets.AWS_REGION }}
          access-key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Build and push with Docker
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          registry: ${{ secrets.AWS_ECR_REGISTRY }}
          tags: latest
